language: node_js
node_js:
- '4.2'
before_script:
- npm install -g grunt-cli
env:
  global:
    secure: MqRjvijLuuKDyeV6acMgVPRem0GDAkAwWm2GhcUI0wLxx7HBHK+ZHMdD6YMZhsqGn1yXPJm6/qeBF4WabwK7d/XV6VG2wNM2f2qvp+ddQGDpS1gp8on1/+c10ndg970BG6MF45hAeoki8vyNcpjmP1tQ8itSyaXQ52MPjcPPoUY=
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: AFu6k5B3jF3MLXElUGWJkrf3E7Xpa6cB+mfoYRrvt95avjKXjDs92s90yVXqIWsUhN77G+hs4FoUymu5wP/G1faTpUjj/MUsylicJtz4nfDVNCFWkjFtc60qAGRp2pqdekWuMkR0gc2X3Mbcs+rlZSAoQs4qi+sygJg1e6bqIX8=
  on:
    tags: true
    repo: noflo/noflo-github
